# Generated by Django 4.2.2 on 2023-11-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0008_remove_question_answers_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='question_answers', to='qa_app.answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='qa_app.question', verbose_name='Вопрос'),
        ),
    ]
