# Generated by Django 4.0.10 on 2023-11-26 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_app', '0009_question_answers_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_authors', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
