# Generated by Django 4.2.2 on 2024-01-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0011_historicaltag_historicalquestion_historicalcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
